import type { DemoPreset, IntelligenceResult } from "./types";

export const demoPresets: DemoPreset[] = [
  {
    id: "verified-fullstack",
    title: "Full-Stack Dev Certificate",
    subtitle: "Authentic & Blockchain Verified",
    badge: "LOW RISK · MATCH",
    riskLevel: "LOW",
    result: {
      credential: {
        credential_id: "CRD-94F2B7A1C8E0",
        original_filename: "stanford-fullstack-diploma.pdf",
        file_type: "PDF",
        mime_type: "application/pdf",
        file_size_bytes: 284192,
        sha256_hash: "a85eb354bcb3ea0f98ffbe996e31c90da6f5c6d014f85a60a3a81a6b5d452ca2",
        status: "COMPLETED",
        created_at: "2026-09-17T09:15:00Z",
      },
      document_processing: {
        credential_id: "CRD-94F2B7A1C8E0",
        extraction_method: "NATIVE",
        text_available: true,
        total_pages: 1,
        average_ocr_confidence: 0.99,
        extracted_text_preview: "Stanford Institute of Advanced Technology — Certificate of Professional Mastery. This certifies that Alex Morgan has demonstrated excellence in Full-Stack Engineering, successfully mastering React.js, TypeScript, Node.js, PostgreSQL, Docker containerization, and RESTful API architecture.",
        full_text: "STANFORD INSTITUTE OF ADVANCED TECHNOLOGY\nDivision of Professional Education & Computational Sciences\n\nCERTIFICATE OF PROFESSIONAL MASTERY\n\nThis certifies that\nALEX MORGAN\n\nhas demonstrated proven excellence in the curriculum of\nFull-Stack Software Architecture & Cloud Engineering\n\nHaving completed comprehensive coursework and capstone evaluations covering:\n• React.js & TypeScript front-end applications\n• Node.js & Express distributed microservices\n• PostgreSQL relational modeling & query optimization\n• Docker containerization & CI/CD deployment pipelines\n• RESTful API architecture and secure session management\n\nIssued on: June 14, 2026\nCredential ID: CRD-94F2B7A1C8E0\nDean of Engineering: Dr. Elena Rostova\nRegistrar: Marcus Vance, Ed.D.",
        extracted_at: "2026-09-17T09:15:02Z",
        status: "PROCESSED",
      },
      authenticity_risk: {
        credential_id: "CRD-94F2B7A1C8E0",
        risk_score: 8,
        risk_level: "LOW",
        signals: [
          {
            signal_type: "font_consistency",
            severity: "LOW",
            description: "Typography is consistent with standard academic publishing compilers (2 unified font families: CMUSerif-Roman and CMUSerif-Bold).",
          },
          {
            signal_type: "linearized_pdf_structure",
            severity: "LOW",
            description: "PDF file structure conforms strictly to PDF/A archival standards with intact cross-reference table.",
          },
        ],
        explanations: [
          "Document exhibits exemplary authenticity metrics with clean typesetting and verified cryptographic integrity.",
          "Standard academic publishing toolchain detected (pdfTeX 1.40.24) with no post-compilation visual raster modifications.",
          "Authenticity signals guide evaluation; they do not replace direct issuer validation.",
        ],
      },
      integrity: {
        algorithm: "SHA-256",
        hash: "a85eb354bcb3ea0f98ffbe996e31c90da6f5c6d014f85a60a3a81a6b5d452ca2",
        blockchain_registered: true,
        integrity_status: "MATCH",
      },
      blockchain_registration: {
        credential_id: "CRD-94F2B7A1C8E0",
        algorithm: "SHA-256",
        artifact_hash: "a85eb354bcb3ea0f98ffbe996e31c90da6f5c6d014f85a60a3a81a6b5d452ca2",
        registered: true,
        contract_address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        transaction_hash: "0x4b7f920875c786a347962453c51379ec8027725916d7a59960ff60f1c30538f9",
        block_number: 19823412,
        network_id: "31337 (Local Dev Ledger / Sepolia Testnet)",
        registered_at: "2026-09-17T09:15:05Z",
      },
      metadata: {
        author: "Registrar Office — SIAT",
        producer: "pdfTeX-1.40.24",
        creator: "LaTeX with hyperref package",
        creation_date: "2026-06-14T10:00:00Z",
        modification_date: "2026-06-14T10:00:00Z",
        raw_metadata: {
          Format: "PDF-1.7",
          Title: "Alex Morgan - Certificate of Professional Mastery",
          Subject: "Full-Stack Software Architecture",
          Keywords: "Engineering, React, Node.js, PostgreSQL",
          Trapped: "False",
          PTEX_Fullbanner: "This is pdfTeX, Version 3.141592653-2.6-1.40.24",
        },
        structural_info: {
          page_count: 1,
          total_text_blocks: 14,
          total_images: 1,
          total_drawings: 6,
          page_dimensions: [{ page: 1, width: 842.0, height: 595.0 }],
          fonts: [
            { name: "CMUSerif-Roman", type: "Type1", page: 1, encoding: "Custom", sizes: [10.0, 12.0, 14.0, 16.0] },
            { name: "CMUSerif-Bold", type: "Type1", page: 1, encoding: "Custom", sizes: [18.0, 24.0, 32.0] },
          ],
          headings: [
            { text: "STANFORD INSTITUTE OF ADVANCED TECHNOLOGY", size: 24.0, font: "CMUSerif-Bold", page: 1 },
            { text: "CERTIFICATE OF PROFESSIONAL MASTERY", size: 32.0, font: "CMUSerif-Bold", page: 1 },
            { text: "ALEX MORGAN", size: 28.0, font: "CMUSerif-Bold", page: 1 },
          ],
          embedded_images: [
            { xref: 8, page: 1, width: 450, height: 450, colorspace: "DeviceRGB", extension: "png" },
          ],
        },
      },
      skills: [
        {
          canonical_skill: "React",
          detected_term: "React.js",
          category: "Frontend Development",
          evidence: {
            text: "completed comprehensive coursework covering React.js & TypeScript front-end applications",
            page_number: 1,
            confidence_weight: 1.0,
          },
          competency_score: 90,
          confidence_score: 98,
          competency_reasons: [
            "Skill is explicitly mentioned in credential curriculum requirements.",
            "Capstone evaluation confirmed practical mastery.",
            "High academic weight assigned to comprehensive coursework.",
          ],
          confidence_reasons: [
            "High-quality native PDF text extraction.",
            "Exact canonical match with alias normalization (React.js → React).",
            "Zero optical noise in text layer.",
          ],
        },
        {
          canonical_skill: "TypeScript",
          detected_term: "TypeScript",
          category: "Frontend Development",
          evidence: {
            text: "React.js & TypeScript front-end applications with modular state architecture",
            page_number: 1,
            confidence_weight: 1.0,
          },
          competency_score: 85,
          confidence_score: 95,
          competency_reasons: [
            "Explicit programming language requirement in core curriculum.",
            "Evaluated in combination with modern UI component design.",
          ],
          confidence_reasons: [
            "High-quality native text parsing.",
            "Direct exact match in structured text block.",
          ],
        },
        {
          canonical_skill: "Node.js",
          detected_term: "Node.js",
          category: "Backend Development",
          evidence: {
            text: "Node.js & Express distributed microservices with asynchronous concurrency",
            page_number: 1,
            confidence_weight: 1.0,
          },
          competency_score: 85,
          confidence_score: 96,
          competency_reasons: [
            "Core backend runtime explicitly certified.",
            "Distributed services implementation demonstrated in coursework.",
          ],
          confidence_reasons: [
            "Exact keyword identification in verified credential.",
            "No linguistic ambiguity in context.",
          ],
        },
        {
          canonical_skill: "PostgreSQL",
          detected_term: "PostgreSQL",
          category: "Database & Storage",
          evidence: {
            text: "PostgreSQL relational modeling & query optimization",
            page_number: 1,
            confidence_weight: 0.95,
          },
          competency_score: 80,
          confidence_score: 94,
          competency_reasons: [
            "Relational modeling and optimization certified.",
            "Direct syllabus evidence present.",
          ],
          confidence_reasons: [
            "Native PDF text extraction.",
            "Standard technical skill term match.",
          ],
        },
        {
          canonical_skill: "Docker",
          detected_term: "Docker",
          category: "DevOps & Cloud",
          evidence: {
            text: "Docker containerization & CI/CD deployment pipelines",
            page_number: 1,
            confidence_weight: 0.9,
          },
          competency_score: 75,
          confidence_score: 92,
          competency_reasons: [
            "Modern deployment toolchain proficiency documented.",
            "CI/CD pipeline construction verified in curriculum.",
          ],
          confidence_reasons: [
            "Clear technical noun extracted from verified PDF stream.",
          ],
        },
      ],
    },
  },
  {
    id: "edited-cloud-cert",
    title: "Cloud Architect Diploma",
    subtitle: "Image Editing Signals Detected",
    badge: "MEDIUM RISK · MATCH",
    riskLevel: "MEDIUM",
    result: {
      credential: {
        credential_id: "CRD-37C82D1E4A9B",
        original_filename: "aws-solutions-architect-pro.pdf",
        file_type: "PDF",
        mime_type: "application/pdf",
        file_size_bytes: 412672,
        sha256_hash: "7f9c2d1e8a4b6c3f0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3f",
        status: "COMPLETED",
        created_at: "2026-09-17T11:20:00Z",
      },
      document_processing: {
        credential_id: "CRD-37C82D1E4A9B",
        extraction_method: "NATIVE",
        text_available: true,
        total_pages: 1,
        average_ocr_confidence: 0.96,
        extracted_text_preview: "AWS Certified Solutions Architect — Professional. Validation ID: AWS-PR-99210. Awarded to Jordan Lee for architecting resilient distributed cloud architectures, Terraform infrastructure-as-code, and Kubernetes orchestration.",
        full_text: "AMAZON WEB SERVICES TRAINING & CERTIFICATION\n\nAWS Certified Solutions Architect — Professional\n\nThis credential is presented to\nJORDAN LEE\n\nfor demonstrating deep technical acumen in:\n• Designing and deploying dynamically scalable and highly available AWS systems\n• Infrastructure as Code with Terraform and CloudFormation\n• Container orchestration utilizing Amazon EKS and Kubernetes\n• Python automation scripts for cloud governance and cost optimization\n\nValidation Number: AWS-PR-99210\nIssue Date: March 22, 2025\nExpiration Date: March 22, 2028",
        extracted_at: "2026-09-17T11:20:03Z",
        status: "PROCESSED",
      },
      authenticity_risk: {
        credential_id: "CRD-37C82D1E4A9B",
        risk_score: 46,
        risk_level: "MEDIUM",
        signals: [
          {
            signal_type: "editing_software_producer",
            severity: "MEDIUM",
            description: "Producer tag indicates Adobe Photoshop 24.2 (Creative Cloud), uncommon for official automated certification issuers.",
          },
          {
            signal_type: "font_family_dispersion",
            severity: "MEDIUM",
            description: "Document contains 6 distinct font families with disparate kerning models (Calibri, Arial-BoldMT, Impact, Times-Roman, MyriadPro-Regular, Courier).",
          },
          {
            signal_type: "timestamp_discrepancy",
            severity: "LOW",
            description: "Modification date (September 2026) is 544 days after the stated certificate issuance date (March 2025).",
          },
        ],
        explanations: [
          "File integrity hash matches the stored record, but structural signals suggest manual desktop editing.",
          "Adobe Photoshop metadata signature detected in document properties.",
          "6 distinct font families detected in a single-page certificate, which frequently correlates with template modifications.",
          "Risk signals guide manual review and do not constitute proof of fraudulent intent.",
        ],
      },
      integrity: {
        algorithm: "SHA-256",
        hash: "7f9c2d1e8a4b6c3f0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3f",
        blockchain_registered: true,
        integrity_status: "MATCH",
      },
      blockchain_registration: {
        credential_id: "CRD-37C82D1E4A9B",
        algorithm: "SHA-256",
        artifact_hash: "7f9c2d1e8a4b6c3f0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3f",
        registered: true,
        contract_address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        transaction_hash: "0x89e21df91278ba01cd5e4932087c0934ea61d09b62a45012fcd909e421a8b13c",
        block_number: 19823460,
        network_id: "31337 (Local Dev Ledger / Sepolia Testnet)",
        registered_at: "2026-09-17T11:20:06Z",
      },
      metadata: {
        author: "Creative Dept",
        producer: "Adobe Photoshop 24.2 (Windows)",
        creator: "Adobe PDF Library 17.0",
        creation_date: "2025-03-22T08:00:00Z",
        modification_date: "2026-09-17T11:18:22Z",
        raw_metadata: {
          Producer: "Adobe Photoshop 24.2 (Windows)",
          CreatorTool: "Adobe Photoshop 24.2",
          ModifyDate: "2026-09-17T11:18:22Z",
          CreateDate: "2025-03-22T08:00:00Z",
          MetadataDate: "2026-09-17T11:18:22Z",
        },
        structural_info: {
          page_count: 1,
          total_text_blocks: 9,
          total_images: 3,
          total_drawings: 1,
          page_dimensions: [{ page: 1, width: 792.0, height: 612.0 }],
          fonts: [
            { name: "MyriadPro-Regular", type: "TrueType", page: 1, sizes: [12.0] },
            { name: "Arial-BoldMT", type: "TrueType", page: 1, sizes: [16.0, 20.0] },
            { name: "Impact", type: "TrueType", page: 1, sizes: [28.0] },
            { name: "Times-Roman", type: "Type1", page: 1, sizes: [14.0] },
            { name: "Calibri", type: "TrueType", page: 1, sizes: [11.0] },
            { name: "Courier", type: "Type1", page: 1, sizes: [10.0] },
          ],
          headings: [
            { text: "AWS Certified Solutions Architect — Professional", size: 28.0, font: "Impact", page: 1 },
            { text: "JORDAN LEE", size: 20.0, font: "Arial-BoldMT", page: 1 },
          ],
          embedded_images: [
            { xref: 4, page: 1, width: 800, height: 600, colorspace: "DeviceRGB", extension: "jpeg" },
            { xref: 7, page: 1, width: 250, height: 250, colorspace: "DeviceRGB", extension: "png" },
            { xref: 9, page: 1, width: 120, height: 120, colorspace: "DeviceRGB", extension: "png" },
          ],
        },
      },
      skills: [
        {
          canonical_skill: "AWS",
          detected_term: "AWS",
          category: "Cloud Computing",
          evidence: {
            text: "AWS Certified Solutions Architect — Professional for designing scalable and highly available AWS systems",
            page_number: 1,
            confidence_weight: 1.0,
          },
          competency_score: 85,
          confidence_score: 98,
          competency_reasons: [
            "High-level certification title directly confirms AWS architecture competency.",
            "Specific multi-tier cloud infrastructure scope mentioned.",
          ],
          confidence_reasons: [
            "Prominent headline text extraction.",
            "Canonical terminology aligned with industry standard.",
          ],
        },
        {
          canonical_skill: "Terraform",
          detected_term: "Terraform",
          category: "DevOps & Infrastructure",
          evidence: {
            text: "Infrastructure as Code with Terraform and CloudFormation",
            page_number: 1,
            confidence_weight: 0.9,
          },
          competency_score: 80,
          confidence_score: 95,
          competency_reasons: [
            "Infrastructure as Code implementation verified.",
            "Standard declarative provisioning context.",
          ],
          confidence_reasons: [
            "Exact skill term identified in credential text block.",
          ],
        },
        {
          canonical_skill: "Kubernetes",
          detected_term: "Kubernetes",
          category: "DevOps & Infrastructure",
          evidence: {
            text: "Container orchestration utilizing Amazon EKS and Kubernetes",
            page_number: 1,
            confidence_weight: 0.85,
          },
          competency_score: 75,
          confidence_score: 94,
          competency_reasons: [
            "Enterprise container orchestration experience recognized.",
          ],
          confidence_reasons: [
            "Direct match in native document text.",
          ],
        },
        {
          canonical_skill: "Python",
          detected_term: "Python",
          category: "Backend Development",
          evidence: {
            text: "Python automation scripts for cloud governance and cost optimization",
            page_number: 1,
            confidence_weight: 0.8,
          },
          competency_score: 70,
          confidence_score: 92,
          competency_reasons: [
            "Automation and scripting capability documented.",
          ],
          confidence_reasons: [
            "Direct language keyword identification.",
          ],
        },
      ],
    },
  },
  {
    id: "tampered-cybersec",
    title: "Tampered Cybersecurity Cert",
    subtitle: "Cryptographic Hash Mismatch",
    badge: "HIGH RISK · MISMATCH",
    riskLevel: "HIGH",
    result: {
      credential: {
        credential_id: "CRD-15E84A9D3F72",
        original_filename: "cissp-security-practitioner-tampered.pdf",
        file_type: "PDF",
        mime_type: "application/pdf",
        file_size_bytes: 524288,
        sha256_hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        status: "COMPLETED",
        created_at: "2026-09-17T14:05:00Z",
      },
      document_processing: {
        credential_id: "CRD-15E84A9D3F72",
        extraction_method: "OCR",
        text_available: true,
        total_pages: 1,
        average_ocr_confidence: 0.76,
        extracted_text_preview: "INTERNATIONAL INFORMATION SECURITY CONSORTIUM — Master Security Analyst. Awarded to Jonathan Archer [OVERPRINT DETECTED]. Skills: Penetration Testing, Wireshark, Cryptography.",
        full_text: "INTERNATIONAL INFORMATION SECURITY CONSORTIUM (IISC)\n\nCERTIFIED INFORMATION SYSTEMS SECURITY PROFESSIONAL\n\nThis is to certify that\nJONATHAN ARCHER\n\nhas fulfilled all security board qualifications in:\n• Advanced Penetration Testing & Vulnerability Assessment\n• Deep Packet Analysis with Wireshark\n• Applied Cryptography & PKI Key Management\n• Linux Hardening & Kernel Security Modules\n\nStatus: Certified Security Fellow\nRegistered Hash on Ledger: a091e77f... [DOES NOT MATCH FILE BYTES]",
        extracted_at: "2026-09-17T14:05:04Z",
        status: "PROCESSED",
      },
      authenticity_risk: {
        credential_id: "CRD-15E84A9D3F72",
        risk_score: 88,
        risk_level: "HIGH",
        signals: [
          {
            signal_type: "cryptographic_hash_mismatch",
            severity: "CRITICAL",
            description: "The submitted file's SHA-256 byte digest does not match the immutable hash registered on the ledger.",
          },
          {
            signal_type: "hidden_text_layer_overlay",
            severity: "HIGH",
            description: "OCR analysis discovered secondary overlaid text bounding box covering original recipient name.",
          },
          {
            signal_type: "scrubbed_metadata_streams",
            severity: "HIGH",
            description: "Document creation metadata and software provenance tags have been purged or corrupted.",
          },
          {
            signal_type: "inconsistent_font_kerning",
            severity: "MEDIUM",
            description: "Character spacing and baseline jitter detected in candidate name line compared to document body.",
          },
        ],
        explanations: [
          "CRITICAL: Cryptographic integrity check failed. The file submitted differs from the original registered bytes.",
          "Visual layer anomaly: Detected overlapping vector objects and text overlays in candidate identity region.",
          "Metadata scrubbing detected: standard PDF metadata stream replaced with blank or corrupted headers.",
          "These findings indicate physical tampering with the artifact bytes after cryptographic registration.",
        ],
      },
      integrity: {
        algorithm: "SHA-256",
        hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        blockchain_registered: true,
        integrity_status: "MISMATCH",
      },
      blockchain_registration: {
        credential_id: "CRD-15E84A9D3F72",
        algorithm: "SHA-256",
        artifact_hash: "a091e77f6b8c4d2e1a3b5c7d9e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f",
        registered: true,
        contract_address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        transaction_hash: "0x23a109fe8251cd98f09b52123d4e89124a9cb54f0119842dc7e502c3491ba8ef",
        block_number: 19823502,
        network_id: "31337 (Local Dev Ledger / Sepolia Testnet)",
        registered_at: "2026-09-17T14:00:00Z",
      },
      metadata: {
        author: null,
        producer: "Unknown / Scrubbed",
        creator: "Unknown",
        creation_date: null,
        modification_date: "2026-09-17T14:03:12Z",
        raw_metadata: {
          Notice: "Metadata stream cleared or modified by external byte editor",
        },
        structural_info: {
          page_count: 1,
          total_text_blocks: 6,
          total_images: 2,
          total_drawings: 12,
          page_dimensions: [{ page: 1, width: 842.0, height: 595.0 }],
          fonts: [
            { name: "Helvetica-Bold", type: "Type1", page: 1, sizes: [22.0] },
            { name: "TimesNewRomanPSMT", type: "TrueType", page: 1, sizes: [12.0, 16.0] },
            { name: "ArialMT", type: "TrueType", page: 1, sizes: [20.0] },
          ],
          headings: [
            { text: "CERTIFIED INFORMATION SYSTEMS SECURITY PROFESSIONAL", size: 22.0, font: "Helvetica-Bold", page: 1 },
            { text: "JONATHAN ARCHER", size: 20.0, font: "ArialMT", page: 1 },
          ],
          embedded_images: [
            { xref: 2, page: 1, width: 600, height: 600, colorspace: "DeviceGray", extension: "png" },
          ],
        },
      },
      skills: [
        {
          canonical_skill: "Penetration Testing",
          detected_term: "Penetration Testing",
          category: "Cybersecurity & Infosec",
          evidence: {
            text: "Advanced Penetration Testing & Vulnerability Assessment",
            page_number: 1,
            confidence_weight: 0.85,
          },
          competency_score: 85,
          confidence_score: 88,
          competency_reasons: [
            "Explicit mention of penetration testing in certification text.",
          ],
          confidence_reasons: [
            "Extracted via OCR with moderate character confidence.",
          ],
        },
        {
          canonical_skill: "Wireshark",
          detected_term: "Wireshark",
          category: "Cybersecurity & Infosec",
          evidence: {
            text: "Deep Packet Analysis with Wireshark",
            page_number: 1,
            confidence_weight: 0.8,
          },
          competency_score: 80,
          confidence_score: 85,
          competency_reasons: [
            "Packet analysis and protocol diagnostics mentioned.",
          ],
          confidence_reasons: [
            "Standard technical tool keyword recognized.",
          ],
        },
        {
          canonical_skill: "Linux",
          detected_term: "Linux",
          category: "Operating Systems",
          evidence: {
            text: "Linux Hardening & Kernel Security Modules",
            page_number: 1,
            confidence_weight: 0.8,
          },
          competency_score: 75,
          confidence_score: 88,
          competency_reasons: [
            "OS hardening and kernel security configuration certified.",
          ],
          confidence_reasons: [
            "Direct match in extracted text.",
          ],
        },
      ],
    },
  },
  {
    id: "scanned-transcript",
    title: "Scanned Academic Transcript",
    subtitle: "Optical Character Recognition (OCR)",
    badge: "LOW RISK · OCR MODE",
    riskLevel: "LOW",
    result: {
      credential: {
        credential_id: "CRD-52A18C3F9D04",
        original_filename: "polytechnic-engineering-transcript.png",
        file_type: "PNG",
        mime_type: "image/png",
        file_size_bytes: 1845200,
        sha256_hash: "3a4f6e8b1c2d0f9e8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f",
        status: "COMPLETED",
        created_at: "2026-09-17T15:40:00Z",
      },
      document_processing: {
        credential_id: "CRD-52A18C3F9D04",
        extraction_method: "OCR",
        text_available: true,
        total_pages: 1,
        average_ocr_confidence: 0.88,
        extracted_text_preview: "METROPOLITAN POLYTECHNIC UNIVERSITY — Official Academic Record. Student: Samantha Chen. Program: Computer Systems Engineering. Coursework: Algorithms & Data Structures, C++, Java, Computer Architecture.",
        full_text: "METROPOLITAN POLYTECHNIC UNIVERSITY\nOffice of the University Registrar\n\nOFFICIAL ACADEMIC RECORD TRANSCRIPT\n\nStudent Name: Samantha Chen\nStudent ID: ENG-2022-8819\nFaculty of Applied Sciences\n\nCOMPLETED COURSEWORK & ASSESSMENTS:\n• CS301: Advanced Data Structures & Algorithms (Grade: A)\n• CS304: Systems Programming in C++ and Unix API (Grade: A-)\n• CS308: Enterprise Software Engineering with Java & Spring (Grade: A)\n• CS412: Distributed Database Systems & SQL Optimization (Grade: A)\n• CS480: Capstone Software Architecture Project (Grade: A+)\n\nCumulative GPA: 3.92 / 4.00\nDegree Conferred: Bachelor of Science in Computer Systems Engineering",
        extracted_at: "2026-09-17T15:40:05Z",
        status: "PROCESSED",
      },
      authenticity_risk: {
        credential_id: "CRD-52A18C3F9D04",
        risk_score: 22,
        risk_level: "LOW",
        signals: [
          {
            signal_type: "optical_character_recognition",
            severity: "LOW",
            description: "Document was processed using Tesseract optical character recognition fallback due to raster image input.",
          },
          {
            signal_type: "paper_grain_and_skew",
            severity: "LOW",
            description: "Sub-degree skew (0.4°) and scanner dot-matrix background typical of authentic physical printouts.",
          },
        ],
        explanations: [
          "Document processed smoothly through Tesseract OCR with high average word confidence (88%).",
          "Raster image characteristics are consistent with genuine scanned physical documents.",
          "Authenticity signals guide review; they do not prove forgery or confirm issuer authenticity.",
        ],
      },
      integrity: {
        algorithm: "SHA-256",
        hash: "3a4f6e8b1c2d0f9e8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f",
        blockchain_registered: true,
        integrity_status: "MATCH",
      },
      blockchain_registration: {
        credential_id: "CRD-52A18C3F9D04",
        algorithm: "SHA-256",
        artifact_hash: "3a4f6e8b1c2d0f9e8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f",
        registered: true,
        contract_address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        transaction_hash: "0x12c98a760b24dc918ef2301492ba8712df98c41098ef3241ab982c76109df432",
        block_number: 19823544,
        network_id: "31337 (Local Dev Ledger / Sepolia Testnet)",
        registered_at: "2026-09-17T15:40:08Z",
      },
      metadata: {
        author: "Registrar Imaging Scanner",
        producer: "Canon DR-G2140 Scanner Driver 2.1",
        creator: "Document Imaging Pipeline",
        creation_date: "2026-05-30T14:22:10Z",
        modification_date: "2026-05-30T14:22:10Z",
        raw_metadata: {
          ImageWidth: 2480,
          ImageHeight: 3508,
          DPI: 300,
          ColorMode: "RGB 24-bit",
          ScannerModel: "Canon DR-G2140",
        },
        structural_info: {
          page_count: 1,
          total_text_blocks: 18,
          total_images: 1,
          total_drawings: 0,
          page_dimensions: [{ page: 1, width: 2480, height: 3508 }],
          fonts: [],
          headings: [
            { text: "METROPOLITAN POLYTECHNIC UNIVERSITY", size: 26.0, page: 1 },
            { text: "OFFICIAL ACADEMIC RECORD TRANSCRIPT", size: 20.0, page: 1 },
          ],
          embedded_images: [
            { xref: 1, page: 1, width: 2480, height: 3508, colorspace: "RGB", extension: "png" },
          ],
        },
      },
      skills: [
        {
          canonical_skill: "C++",
          detected_term: "C++",
          category: "Systems Programming",
          evidence: {
            text: "CS304: Systems Programming in C++ and Unix API (Grade: A-)",
            page_number: 1,
            confidence_weight: 0.95,
          },
          competency_score: 85,
          confidence_score: 92,
          competency_reasons: [
            "Formal university grading and high academic mark (A-).",
            "Systems programming context confirms deep memory management knowledge.",
          ],
          confidence_reasons: [
            "Extracted via OCR with clear character boundaries.",
            "Standard academic course code context.",
          ],
        },
        {
          canonical_skill: "Java",
          detected_term: "Java",
          category: "Enterprise Software",
          evidence: {
            text: "CS308: Enterprise Software Engineering with Java & Spring (Grade: A)",
            page_number: 1,
            confidence_weight: 0.95,
          },
          competency_score: 85,
          confidence_score: 94,
          competency_reasons: [
            "University course completed with grade A.",
            "Enterprise software engineering syllabus.",
          ],
          confidence_reasons: [
            "Accurately extracted through OCR.",
          ],
        },
        {
          canonical_skill: "Data Structures",
          detected_term: "Data Structures",
          category: "Computer Science Core",
          evidence: {
            text: "CS301: Advanced Data Structures & Algorithms (Grade: A)",
            page_number: 1,
            confidence_weight: 0.9,
          },
          competency_score: 90,
          confidence_score: 95,
          competency_reasons: [
            "Top grade (A) in advanced computational foundational course.",
          ],
          confidence_reasons: [
            "Prominent course title found in transcript.",
          ],
        },
        {
          canonical_skill: "Algorithms",
          detected_term: "Algorithms",
          category: "Computer Science Core",
          evidence: {
            text: "CS301: Advanced Data Structures & Algorithms (Grade: A)",
            page_number: 1,
            confidence_weight: 0.9,
          },
          competency_score: 90,
          confidence_score: 95,
          competency_reasons: [
            "Advanced algorithmic problem solving verified with grade A.",
          ],
          confidence_reasons: [
            "High confidence course recognition.",
          ],
        },
      ],
    },
  },
];

export const demoResult: IntelligenceResult = demoPresets[0].result;

